### ISSUE TITLE
CMPO - asymmetric organelle distribution phenotype

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/CMPO#2]
asymmetric organelle distribution phenotype

From https://elifesciences.org/articles/24060.

Doesn't specifiy which organelles exactly but they are looking at mitochondria and ER

Could be child of
cellular component phenotype

 http://www.ebi.ac.uk/cmpo/CMPO_0000259

**Comment by eleanorwilliams** [comment]
New term now added in CMPO 
- asymmetric cellular component phenotype http://www.ebi.ac.uk/cmpo/CMPO_0000454.
This issue can be closed. @siiraa @simonjupp
