### ISSUE TITLE
new CMPO phenotypes - enrichment and de-enrichment of mainly cell morphology phenotypes

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/CMPO#3]
Phenotypes from this paper http://dx.doi.org/10.1101/092403

All about enrichment and de-enrichment of sub populations of cells which we have also seen in other HCS papers but perhaps not adequately described.  Phenotypes identified are:

enriched for extremely elongated
enriched for slightly elongated
enriched for extremely triangular
enriched for huge
enriched for slightly large
enriched for small asymmetric cells
enriched for multi-nucleate
enriched for telophase/late telophase
enriched for disjoint bright mito
enriched for apoptotic
de-enriched for slightly elongated
de-enriched for extremely elongated
de-enriched for extremely triangular
de-enriched for huge
de-enriched for slightly large
de-enriched for small asymmetric cells
de-enriched for multi-nucleate
de-enriched for telophase/late telophase
de-enriched for disjoint bright mito
slightly low cell density
low cell density
normal cell density

**Comment by eleanorwilliams** [comment]
We decided to just use the single cell phenotypes for the enriched terms for now and so this issue can be closed.  We may revisit the population vs. single cell phenotypes in future or handle them within the Image Data Resource itself instead. @siiraa @simonjupp
