### ISSUE TITLE
Various new CMPO terms

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/CMPO#4]
New terms in spreadsheet attached. Some still under discussion with author.
Author phenotypes are

high nucleus/cell area
low nucleus/cell area
high Neighbor Fraction
low Neighbor Fraction
high local density
low local density
low nuclear roundness
doughnut nuclei
high total YAP/TAZ
low total YAP/TAZ
high YAP/TAZ ratio
low YAP/TAZ ratio

[NewCMPOTermsForidr0030.xlsx](https://github.com/EBISPOT/CMPO/files/1453986/NewCMPOTermsForidr0030.xlsx)

**Comment by eleanorwilliams** [comment]
The last two terms that needed to be added are now in CMPO. 

- decreased nucleus to cell area ratio http://www.ebi.ac.uk/cmpo/CMPO_0000457
- increased nucleus to cell area ratio http://www.ebi.ac.uk/cmpo/CMPO_0000458

@siiraa @simonjupp This issue can now been closed. Thanks.
